/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class by_moonx_backend_mcapi_MCAPI */

#ifndef _Included_by_moonx_backend_mcapi_MCAPI
#define _Included_by_moonx_backend_mcapi_MCAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     by_moonx_backend_mcapi_MCAPI
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_by_moonx_backend_mcapi_MCAPI_init
  (JNIEnv *, jobject);

/*
 * Class:     by_moonx_backend_mcapi_MCAPI
 * Method:    destroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_by_moonx_backend_mcapi_MCAPI_destroy
  (JNIEnv *, jobject);

/*
 * Class:     by_moonx_backend_mcapi_MCAPI
 * Method:    eclipticPosition
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_by_moonx_backend_mcapi_MCAPI_eclipticPosition
  (JNIEnv *, jobject);

/*
 * Class:     by_moonx_backend_mcapi_MCAPI
 * Method:    phaseInformation
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_by_moonx_backend_mcapi_MCAPI_phaseInformation
  (JNIEnv *, jobject);

/*
 * Class:     by_moonx_backend_mcapi_MCAPI
 * Method:    newMoon
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_by_moonx_backend_mcapi_MCAPI_newMoon
  (JNIEnv *, jobject);

/*
 * Class:     by_moonx_backend_mcapi_MCAPI
 * Method:    enumeratePhases
 * Signature: (DD)I
 */
JNIEXPORT jint JNICALL Java_by_moonx_backend_mcapi_MCAPI_enumeratePhases
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     by_moonx_backend_mcapi_MCAPI
 * Method:    nextPhase
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_by_moonx_backend_mcapi_MCAPI_nextPhase
  (JNIEnv *, jobject);

/*
 * Class:     by_moonx_backend_mcapi_MCAPI
 * Method:    riseCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_by_moonx_backend_mcapi_MCAPI_riseCount
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
